spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}

quota:
  url: http://rate-limiter:8080/quota/telegram-api